spring:
  application:
    name: demo
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: "10MB"
      max-request-size: "10MB"

test:
  property: "property of application.yml"

# default custom logging configuration path
#logging:
#  config: "classpath:logback-spring.xml"
