spring:
  application:
    name: demo
  output:
    ansi:
      enabled: always

test:
  property: "property of application.yml"

# default custom logging configuration path
#logging:
#  config: "classpath:logback-spring.xml"
